ci:
  autoupdate_commit_msg: "📈 Update versions for pre-commit hooks"
  autofix_commit_msg: "🪩 Automated fixes from https://pre-commit.ci"
  autoupdate_schedule: "weekly"
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c" # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "2700fd5671c633760d912769c041bfcde2b9a01b" # frozen: v0.15.22
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes"]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/asottile/pyupgrade
    rev: "75992aaa40730136014f34227e0135f63fc951b4" # frozen: v3.21.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/codespell-project/codespell
    rev: "57b21406f092110c18776e39b0bda50d37c945c8" # frozen: v2.4.3
    hooks:
      - id: codespell
        args: ["--skip=CODE_OF_CONDUCT.md"]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "9337a74165b178ae2c766f60bee7252a0f06f3e8" # frozen: v3.9.5
    hooks:
      - id: prettier
        files: \.(html|md|toml|yml|yaml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: "64a97fb7fa63188393d3215c6e312f5f9c6d0f78" # frozen: v1.27.0
    hooks:
      - id: zizmor
        args: ["--pedantic"]
