name: Build and push Docker images to Docker Hub

on:
    workflow_dispatch:
    push:
        branches:
        - main

jobs:
    build_docker_image:
        # This workflow is only of value to Owner and would always be skipped in forks
        if: github.repository_owner == 'agriyakhetarpal'
        name: Build image
        runs-on: buildjet-2vcpu-ubuntu-2204-arm

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image to Docker Hub
              uses: docker/build-push-action@v5
              with:
                context: .
                file: Dockerfile
                tags: agriyakhetarpal/hugo:latest # To be updated with exact Docker Hub username and image name
                push: false
                platforms: linux/amd64, linux/arm64

            - name: Run tests inside the built Docker image
              run: |
                docker run --rm agriyakhetarpal/hugo:latest hugo version
                docker run --rm agriyakhetarpal/hugo:latest hugo env

            - name: List built image(s)
              run: docker images
