name: Reproducer

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  reproducer:
    name: Build Hugo for Windows i686 with Zig ${{ matrix.zig-toolchain }}
    runs-on: [windows-latest]
    strategy:
      fail-fast: false
      matrix:
        zig-toolchain: [gha, pypi]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: 3.12

      - name: Set up Go toolchain
        id: setup-go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: "1.24.0"
          cache: false
          check-latest: true

      - run: python -m pip install ziglang==0.13.0post1
        if: matrix.zig-toolchain == 'pypi'

      - uses: mlugg/setup-zig@a67e68dc5c8281d9608136d3d7ca1b282213e4ac # v1.2.1
        if: matrix.zig-toolchain == 'gha'
        with:
          version: 0.13.0
          use-cache: false

      - name: Build Hugo (using zig-pypi)
        if: matrix.zig-toolchain == 'pypi'
        env:
          CGO_ENABLED: 1
          CC: "python -m ziglang cc -target x86-windows-gnu"
          CXX: "python -m ziglang c++ -target x86-windows-gnu"
          GOOS: windows
          GOARCH: 386
          GOPATH: ${{ github.workspace }}\gopath
        run: go install -tags extended,withdeploy -ldflags "-extldflags=-static" github.com/gohugoio/hugo@v0.144.2

      - name: Build Hugo (using zig-gha)
        if: matrix.zig-toolchain == 'gha'
        env:
          CGO_ENABLED: 1
          CC: "zig cc -target x86-windows-gnu"
          CXX: "zig c++ -target x86-windows-gnu"
          GOOS: windows
          GOARCH: 386
          GOPATH: ${{ github.workspace }}\gopath
        run: go install -tags extended,withdeploy -ldflags "-extldflags=-static" github.com/gohugoio/hugo@v0.144.2

      - name: Run Hugo
        env:
          GOPATH: ${{ github.workspace }}\gopath
        run: ${{ env.GOPATH }}\bin\hugo.exe version
